export const apiUrl =
  process.env.NODE_ENV !== "production" ? "http://localhost:5000/api" : "";

export const LOCAL_STORAGE_TOKEN_NAME = "lemon-review-book";

export const USERS_LOADED_SUCCESS = "USERS_LOADED_SUCCESS";
export const USERS_LOADED_FAIL = "USERS_LOADED_FAIL";
export const DELETE_USER = "DELETE_USER";
export const ADD_USER = "ADD_USER";

export const CATEGORIES_LOADED_SUCCESS = "CATEGORIES_LOADED_SUCCESS";
export const CATEGORIES_LOADED_FAIL = "CATEGORIES_LOADED_FAIL";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const FIND_CATEGORY = "FIND_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";

export const BOOKS_LOADED_SUCCESS = "BOOKS_LOADED_SUCCESS";
export const BOOKS_LOADED_FAIL = "BOOKS_LOADED_FAIL";
export const BOOKS_BY_CATEGORY_SUCCESS = "BOOKS_BY_CATEGORY_SUCCESS";
export const BOOKS_BY_CATEGORY_FAIL = "BOOKS_BY_CATEGORY_FAIL";
export const GET_BOOK = "GET_BOOK";
export const ADD_BOOK = "ADD_BOOK";
export const FIND_BOOK = "FIND_BOOK";
export const UPDATE_BOOK = "UPDATE_BOOK";
export const DELETE_BOOK = "DELETE_BOOK";
export const UPDATE_VIEW = "UPDATE_VIEW";

export const COMMENTS_LOADED_SUCCESS = "COMMENTS_LOADED_SUCCESS";
export const COMMENTS_LOADED_FAIL = "COMMENTS_LOADED_FAIL";
export const COMMENTS_BY_BOOK_LOADED_SUCCESS =
  "COMMENTS_BY_BOOK_LOADED_SUCCESS";
export const COMMENTS_BY_BOOK_LOADED_FAIL = "COMMENTS_BY_BOOK_LOADED_FAIL";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const ADD_COMMENT = "ADD_COMMENT";
export const FIND_COMMENT = "FIND_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
